### ISSUE TITLE
TypeError: this.field is null

### ISSUE THREAD

**Issue by FeIix** [lalalic/docx2html#9]
This lib was working fine, until a docx throwed an error that breaks JS :

TypeError: this.field is null -  docx2html.min.js:14:19890

I think that a "!" is missing in the following condition :
`if (this.field) this.field = new _field2.default(instruct, this.wDoc, this, type);`

To make it works again I had to change it to :

`if (!this.field) this.field = new _field2.default(instruct, this.wDoc, this, type);`

Nice lib 👍

**Comment by lalalic** [comment]
sorry, can't find the code in latest.
